### PR TITLE
Request to add refack as CommComm member

### PR DESCRIPTION
**Pull request by refack**
It's been 3 (great) months since my request to join as an observer https://github.com/nodejs/community-committee/issues/105.
AFAIK I've attended every meeting during this time, and hopefully I wasn't dead weight...

I would be my honor to be voted in as a member of the committee.
🙏

### CODE REVIEW

**Comment by mhdawson** [comment]
+1

**Comment by williamkapke** [comment]
The wait is over! Welcome @refack!

**Comment by bnb** [comment]
I will put this on today's agenda and we will begin the process of the vote 👍

**Comment by rachelnicole** [comment]
Per the vote, @refack has been voted in as a full member of the Community Committee. 

Welcome refack!

Vote: http://www.decing.com/?tgugh40bcu2j

**Comment by refack** [comment]
Thank you all 🎩

**Comment by dshaw** [comment]
Yay! Let's land this.

**Pull request merged**
