### PR TITLE
Add @JemBijoux as CommComm member

### PR DESCRIPTION
**Pull request by bnb**
Initial pass at adding @JemBijoux as a CommComm member. Can add email address once this passes and they approve. As an observer, @JemBijoux has hit the three month attendance period to become a member.

### CODE REVIEW

**Comment by JemBijoux** [comment]
Hooray! Want me to update this with my actual email though?

**Comment by bnb** [comment]
Yes, I can update it - what is it? 😄

**Comment by JemBijoux** [comment]
`jem@hipmedia.ca`

**Comment by bnb** [comment]
Vote has closed, welcome to the Node.js Community Committee @JemBijoux!

Next steps:
- [ ] Update this PR with your email
- [ ] Add your email to the CommComm alias
- [ ] Add you to the CommComm GitHub team

**Comment by bnb** [comment]
I've completed the tasks listed above. Email has been updated, added to the mailing list via PR, invited to the CommComm team, and removed as an observer from the issue creator tool.

@nodejs/community-committee PTAL – this should be good to merge 👍

**Pull request merged**
