### PR TITLE
doc: remove Dan as champion for user feedback

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Comment by mhdawson** [comment]
@dshaw

**Comment by bnb** [comment]
LGTM, though we should maybe add the Enterprise User Feedback Group since they're still going to remain under us.

**Comment by mhdawson** [comment]
@bnb I did

> | Enterprise Usr Feeback | Ahmad Nassri                   | [mhdawson]      | [nodejs/user-feedback]          |

**Comment by bnb** [comment]
Going to merge this since it's been open for 2 weeks.

**Pull request merged**
