### PR TITLE
Add @chowdhurian as CommComm member

### PR DESCRIPTION
**Pull request by bnb**
Initial pass at adding @chowdhurian as a CommComm member. Can add email address and name once this passes and they approve.

### CODE REVIEW

**Comment by bnb** [comment]
Forgot to mention: As an observer, @chowdhurian has hit the three month attendance period to become a member.

**Comment by chowdhurian** [comment]
Sweet! 🎉

Thanks @bnb! 🙌

My email is manil.chowdhury@gmail.com

**Comment by bnb** [comment]
Vote has closed, welcome to the Node.js Community Committee @chowdhurian!

Next steps:
- [ ] Update this PR with your email
- [ ] Add your email to the CommComm alias
- [ ] Add you to the CommComm GitHub team

**Comment by bnb** [comment]
I've completed the tasks listed above. Email has been updated, added to the mailing list via PR, invited to the CommComm team, and removed as an observer from the issue creator tool.

@nodejs/community-committee PTAL – this should be good to merge 👍

**Pull request merged**
