### PR TITLE
William Kapke - Conduct Commitment

### PR DESCRIPTION
**Pull request by williamkapke**
Please accept this conduct commitment from me. I will honor it even if you decline to accept it. 😉 

Feedback welcome!

### CODE REVIEW

**Comment by bnb** [comment]
Are you submitting this to enable each member of the CommComm to sign (as individual PRs), or for your own personal commitment? I applaud this effort, but want to understand the scope and intended structure of this document.

If we were to enable something like this in the CommComm, it should _probably_ be something anyone in the CommComm or a CommComm team/WG should be able to duplicate or sign and include in this repo, and the structure should follow suit.

**Comment by rachelnicole** [comment]
Did I miss something somewhere else that explains what this is about?

**Comment by renrutnnej** [comment]
I am not comfortable putting my name to a statement like this.

**Comment by williamkapke** [comment]
@rachelnicole Background: there is a proposal in the TSC to specifically exclude our CoC's reach to other public venues. That's fine by me... but I (individually) am specifically opting-in to it. It's what \*I\* believe is right. It is not in my constitution to think others should believe as I do and I do not believe my way of thinking is the "right" way. So, I only did this for myself.

@renrutnnej @bnb Ok. Cool.

It's a PR- feel free to reject it.

**Comment by rachelnicole** [comment]
@williamkapke i appreciate the clarity. 

I do think that we should wait and see how discussions play out before opening any PR's in regards to stuff like this, because this could end up being more divisive with people who disagree with the sentiment even though I know that's not your intention at all.

**Comment by RichardLitt** [comment]
> So, I only did this for myself.

I applaud the effort. But I'm not sure it needs to be here - this can put pressure on those who disagree with it to to sign it, too. It's a slippery slope from there to being enforced. Like @renrutnnej, I wouldn't sign this. But I'm really glad you feel this strongly about it, and I think it's a laudable effort in itself.

**Comment by williamkapke** [comment]
@RichardLitt @brb I'm sorry to hear that. [Some in the community](https://github.com/nodejs/TSC/pull/327#issuecomment-325812649) seem to expect it and make a great case for us to be held to a higher standard.

I hold our leaders to a higher standard. I hope you reconsider your stance.

**Comment by RichardLitt** [comment]
@williamkapke I expect it to a certain extent, too. And I agree that it would make a great reason for us to hold ourselves to a higher standard. And I applaud your efforts for putting this here. 

I disagree with having some people sign it, and not others. That leads to questions why others don't sign it. Those questions cause friction, which can lead to people feeling silenced elsewhere. I don't want that. I want a free and open discourse in all venues, as long as it is healthy, and as long as people are prepared to do the emotional heavy lifting of making sure they don't infringe on other people's rights. 

The reason I won't sign it is that I don't think it is my job to keep all of my ducks in line according to the Node Community, but rather it _is_ my job to be civil inside the Node Community, according to Node's Code of Conduct. As a person with occasional fringe views (which I won't go into here, because they are totally not relevant beyond saying I have them), I do not want to have to limit myself elsewhere because of my involvement in Node. Having you sign this document, and me not, gives a message that I am somehow being obtuse here. I don't want that. However, I am more than happy to abide by the Code of Conduct within Node.

**Comment by bnb** [comment]
Can this be closed? The [membership expectations](https://github.com/nodejs/admin/blob/master/MemberExpectations.md) doc has now landed.

**Pull request closed without merging**
