### PR TITLE
Renamed file extensions to be lower case

### PR DESCRIPTION
**Pull request by nebrius**
This rename makes filenames consistent with the rest of the Node.js org, and fixes some broken links in the process.

### CODE REVIEW

**Comment by williamkapke** [comment]
Hm. Thinking about it... I'm worried that merging this will make things harder for @hackygolucky and the changes in #1. Since that is already a complicated PR to follow... let's hold off on this until it is merged.

**Comment by jasnell** [comment]
Agree on holding off a bit.

**Comment by nebrius** [comment]
> let's hold off on this until it is merged.

Totally makes sense :)

**Comment by nebrius** [comment]
I rebased against master to fix the merge conflict

**Pull request merged**
