### PR TITLE
move @waleedashraf to emeritus

### PR DESCRIPTION
**Pull request by WaleedAshraf**
Hi Team,
Due to personal work, I haven't been much active in CommComm lately and skipped most of the recent meetings.
Better to update my status as emeritus. I'll still be in touch. You can reach out to me through email/Twitter anytime.

It has been a great pleasure to work with the team for almost 3 years. Thanks to everyone for their support. ❤️

### CODE REVIEW

**Comment by WaleedAshraf** [comment]
Also, I think we should move Node.js Collection Initiative to retired and possibly archive the repo. @bnb

**Comment by bnb** [comment]
Thanks for the time and energy you've spent on the Community Committee over the past few years. I hope that we see you again sometime in the not too distant future ❤️

I think we'll probably want to work with the Foundation on a small plan for what to do with the Medium (since they still do post to the Node.js Medium account), but otherwise agree.

**Review by joesepi — APPROVED** [review]
Thanks for all your work @WaleedAshraf. I look forward to working with you in the future. Cheers and good luck!

**Review by bnb — APPROVED** [review]

**Comment by ahmadawais** [comment]
Thanks for all your work and contributions here with Node.js (OpenJS) Foundation and otherwise. I hope to see you again sooner than later. Cheers! Good luck.

**Pull request merged**
