### PR TITLE
Update CoC to reflect current official CoC location.

### PR DESCRIPTION
**Pull request by bnb**
Changes from referencing CoC in TSC repo to CoC in Admin repo.

### CODE REVIEW

**Comment by bnb** [comment]
I believe this should also close out https://github.com/nodejs/community-committee/issues/34 if merged.

**Comment by pup** [comment]
does this need to go through the board or can this be merged?

**Comment by mhdawson** [comment]
It can just be merge

**Comment by pup** [comment]
merging!

**Pull request merged**
