### PR TITLE
First pass at PARTNER_COMMUNITIES.md

### PR DESCRIPTION
**Pull request by bnb**
First pass at creating a basic `PARTNER_COMMUNITIES.md`. Everything is totally up for discussion and revision.

Please feel free to suggest additions and changes, and _make_ those changes (given there's consensus) if you're a CommComm member ❤️

### CODE REVIEW

**Comment by codeekage** [comment]
Is there a definition for a Partner Community?

**Comment by vcarl** [comment]
What level of access does "administrator" entail?

**Comment by WaleedAshraf** [comment]
Related: https://github.com/nodejs/community-committee/issues/326
@codeekage

**Comment by codeekage** [comment]
Thank you @WaleedAshraf

**Comment by codeekage** [comment]
Can [Node Africa](https://github.com/nodejsafrica) be consider a Pattern Community? Are they some certain criteria to be met? 

Please, correct me if I’m wrong to raise that here. :prayer:

**Comment by bnb** [comment]
@vcarl my assumption on what "Administrator" access would entail is that the Collaborator would be enabled to ensure that the Code of Conduct / Moderation Policy are applied.

Does that make sense? 🤔

**Comment by vcarl** [comment]
Hmm, my assumption was that applying the Code of Conduct/Moderation Policy would be more or less public. Are you picturing some kind of automated enforcement tools as well @bnb?

**Comment by vcarl** [comment]
Or am I misunderstanding, and there would be a node representative actually enforcing the rules? That seems less like a "partner" and more like the node org running the chatroom. I'd be happy to adopt the moderation policy/code of conduct, but granting a third party admin rights doesn't sit well with me. 

I'd be willing to talk about moderation access (distinction being control over server settings vs control over messages), but even that feels like handing over a lot of control to individuals I don't really know.

**Comment by mhdawson** [comment]
@vcarl I see the request for "admin rights" as getting to a shared level of trust and I agree that the request is in order to be able to participate in moderation as opposed to anything else.  We may need to tighten up the language on that front.

I don't expect that the individual from the node.js org is going to take over or necessarily even be active in moderating. However, being willing to give that level of access so that they could jump into an issue when it's important is one way of demonstrating a level of commitment to upholding the moderation policy/code of conduct. 

I agree that trust goes both ways, so in a case where a partner is not comfortable trusting the individuals from the Node.js org, then more work/time/collaboration is needed before a `partnership` makes sense.

**Comment by vcarl** [comment]
To me, it shows a lack of trust from the node.js org. It's anticipating that there will be problems where it's necessary for them to jump in and take action, rather than talk to the server moderation team. I've been moderating a group of 3000 React developers for several years, and 95% of the moderating I do is more like mediation–not deleting messages and banning users. That requires no special permissions.

There is a lack of trust because I have reached out numerous times about the chatroom I created, and have been placated each time with no follow up. A core dev announced a competing Discord server within ours (which is both larger and more active), with no indication or communication before hand. I only found this issue because I subscribed to the repo several months ago.

**Comment by mhdawson** [comment]
Sounds like there is context that I don't have since I was not talking about any specific cases just adding my thoughts as to why that requirement made sense to me.

**Comment by bnb** [comment]
@vcarl I think a lot of the prior context that led to this structure lies with a few Node.js communities that have been sources of consistent problems and just as consistently have refused very specific requests around moderation.

> It's anticipating that there will be problems where it's necessary for them to jump in and take action, rather than talk to the server moderation team.

I can see how it could be taken that way. The goal is more to ensure that we can actually protect individuals blessed third-party communities and have a direct path of accountability into the project itself if we fail.

> A core dev announced a competing Discord server within ours (which is both larger and more active), with no indication or communication before hand. I only found this issue because I subscribed to the repo several months ago.

I'm that contributor (although admittedly not a core contributor). There was actually a lot of context behind that decision – about two years of debate that burned out several community members – and I was not aware of your Discord server when I launched it. I believe our discussion about this can actually be found in the discord history if you go back a bit 😅

All that said, I'm totally not opposed to shuttering the Discord server I started – I've not personally had the time to maintain and grow it, and you have indeed done a fantastic job with both Reactiflux and Nodeiflux.

I'd also like to add that I'd hope you don't feel that I've ignored you on this topic as I know we've discussed it in the past, although I would understand if you do. I quite honestly have GitHub notifications almost muted because of how many I get and AFAIK we've never discussed these issues on the platforms I do monitor. Absolutely always happy to respond, it's just that connecting on the right platforms hasn't happened 😬

**Comment by vcarl** [comment]
I don't believe you personally advertised within ours, it was one of the developers. I won't name them because I'm not trying to call them out, but I do think it started us off on the wrong foot. 

One question I have: What benefit does a partner community receive? I don't see any "blessed" communities listed on nodejs.org, and the pseudo-official Discord group doesn't seem to be getting much organic traffic. I believe Node Slackers is one such community, but short of searching the exact name I have a hard time finding it. Without an obvious benefit to my community, I'm not sure why I would want to subject myself to additional processes and stakeholders. In the same vein, without an obvious benefit, revoking the partner status seems like a symbolic gesture.

**Comment by mhdawson** [comment]
In terms of benefits I don't think we'd thought that through so far.  As I remember node-slackers wanted to be listed (or one of our collaborators wanted/thought that made sense) and so we had some discussion on what would be required to do that.

I don't think we've had any discussions on working to convince third parties why they would want to be listed or an effort to actively recruit at this point.

**Comment by bnb** [comment]
@mhdawson's comments are accurate – we will list and share partner communities as partner communities for the time being. Ideally we will also list them in the Community section once the Website Redesign launches. We'd also be open to suggestions / requests if you've got any @vcarl 🤗

Beyond that, I believe this is ready to land as a first stab that is ready for iteration. If someone would like to do the honor of merging, feel free!

**Comment by bnb** [comment]
Going to land this 👍

**Comment by bnb** [comment]
Landed. Time to iterate! If you have additional changes/suggestions/updates you'd like to make to this, please don't hesitate to PR or create an issue ❤️

**Pull request merged**
