### PR TITLE
ci(automation): add Linkinator GitHub Action

### PR DESCRIPTION
**Pull request by bnb**
This PR adds Linkinator's GitHub Action. Theoretically as a GitHub Action, it'll less aggressively hit the GitHub rate limit which we trigger pretty fast. Not hopeful that it'll work on the first try, but hopeful that we can at least eventually get there with Linkinator... especially since it's by @JustinBeckwith who is wonderful.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
If you're running into issues with the GitHub rate limit, you can also add a `retry` option set to `true` now that will automatically respect the `retry-after` HTTP header when GitHub returns a HTTP 429.  I just pulled this up from the linkinator CLI to the action so you can use it 😄

**Comment by bnb** [comment]
@nodejs/community-committee this should be ready to go. The only link that's failing still is one that's fixed in https://github.com/nodejs/community-committee/pull/667. 

Thank you @JustinBeckwith for your help ❤️

**Review by WaleedAshraf — APPROVED** [review]

**Comment by JustinBeckwith** [comment]
Absolutely!  Please if you have any questions at all, I'm always happy to hop in and help.

**Review by joesepi — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
