### PR TITLE
meta: Update CommComm Membership in README.md

### PR DESCRIPTION
**Pull request by bnb**
Updates CommComm Membership list temporarily, removing Bryan as Chair and adding Tracy Hinds as acting Chair.

### CODE REVIEW

**Comment by williamkapke** [comment]
Furthermore, committee chairs do not seem to have a clause for assigning someone in their stead. 

(I admit I was initially confused and thought there was because of the Directors' ability to do so)

**Comment by bnb** [comment]
@williamkapke I asked for the same clarification, and was reassured by @ashleygwilliams that @hackygolucky was indeed the acting chair. 

https://github.com/nodejs/community-committee/pull/124#issue-256011125

**Comment by bnb** [comment]
Again, there's leeway there - didn't mean to insinuate that @ashleygwilliams was certain about it (poor word choice on my part), but it does seem there was agreement.

**Comment by williamkapke** [comment]
@bnb - yeah, I see where the concept came from... but "Acting Chair" is not an official role -so I object to documenting it as if it is.

I **am**, however, 100% behind getting @nebrius's written statement assigning @hackygolucky to be in that role (act in his stead) and documenting that process.

Until then, we need to honor what @nebrius wrote and @hackygolucky is just wonderfully stepping up and volunteering to do some of the work.

**Comment by nebrius** [comment]
As was mentioned earlier, my intention was to stay on as chair until after the election, which I mentioned [here](https://medium.com/@nebrius/why-im-leaving-the-node-js-project-bff946845a77) and [here](https://github.com/nodejs/community-committee/issues/113#issue-252077103). This is why I originally submitted PRs to remove myself from the TSC but did not submit any to remove myself from CommComm.

There seems to have been some miscommunication around this though, and @ashleygwilliams and @hackygolucky got the impression that I resigned from CommComm at the same time I resigned from the TSC, and that there was no chairperson of CommComm. As such, @hackygolucky stepped up to perform the duties of chairperson until a new chairperson was elected.

When I learned of this in a private chat with Ashley, I decided to go ahead and resign from CommComm at that point in time, since the transfer of chairperson duties had already been completed, even if an official chairperson had not been elected. This was opened in https://github.com/nodejs/community-committee/pull/124, but has not been merged yet. So for formalities sake, and to complete the process, I'll formally state things here.

Effective immediately, I hereby resign from the role of chairperson of the Node.js Foundation Community Committee. To ensure continuity of the role of chairperson, I hereby appoint @hackygolucky as the chairperson of CommComm, effective immediately and lasting until an election can be held to appoint the next chairperson via vote of all CommComm members.

**Comment by williamkapke** [comment]
Awesome @nebrius. Thank you- miss you already!

I've approved the PR, as-is, optimistically believing that we will add the language to our governance to officially support this in the future.

**Comment by bnb** [comment]
Thank you for due diligence @nebrius and @williamkapke. I'll merge soon (in 24-48 hours) if there are no further objections.

**Comment by bnb** [comment]
Going to merge 👍

**Pull request merged**
