### PR TITLE
added waleedashraf as member

### PR DESCRIPTION
**Pull request by WaleedAshraf**
Hi Everyone,
I must say that time passes quickly. ⏳ ⌚️. I believe I have met the requirements to join CommComm as a member. You may review the attendance in meeting notes and [here](http://www.nodejsparticipants.info/nodejs/community-committee.html).

Very excited 🎉 😃 and looking forward to make more contribution in Node.js through CommComm.

### CODE REVIEW

**Comment by WaleedAshraf** [comment]
Ping @bnb 😄

**Comment by bnb** [comment]
👋 @WaleedAshraf.

I'll kick this vote off tomorrow. Apologies for the delay, been super busy 😬

**Comment by bnb** [comment]
Vote has been sent to all members! Apologies for the delay 🙏

**Comment by WaleedAshraf** [comment]
👍 no problem 😉

**Comment by bnb** [comment]
Congrats @WaleedAshraf! The CommComm has voted and approved you as a CommComm member with a majority vote.

CommComm Membership Checklist: 

- [ ] Invite to CommComm GitHub Team (and Node.js GitHub org, if not already member)
- [ ] Submit PR to add to the [commcomm email alias](https://github.com/nodejs/email/blob/master/iojs.org/aliases.json#L96)
- [ ] Submit PR to add to the (CommComm README.md](https://github.com/nodejs/community-committee/blob/master/README.md#community-committee-members)

**Comment by bnb** [comment]
Email PR: https://github.com/nodejs/email/pull/100

**Comment by WaleedAshraf** [comment]
Thanks @bnb 
So excited :)
I think we are good to merge this. I'll go with merging my first PR. 👍

**Comment by WaleedAshraf** [comment]
@bnb Just making sure that I didn't miss anything.
Is there something like instructions/on-boarding/dos-don'ts after a new member added to CommComm?

**Comment by refack** [comment]
> Is there something like instructions/on-boarding/dos-don'ts after a new member added to CommComm?

I think the idea is that the "Observation" period is the on-boarding process. Other then that IMHO the only rule in WRT to the private portion of the meetings.

**Comment by WaleedAshraf** [comment]
@refack Thats what I thought. Thanks for clarifying. 👍

**Pull request merged**
