### PR TITLE
Add @codeekage as a Member

### PR DESCRIPTION
**Pull request by bnb**
Adds @codeekage as a member.

CommComm Membership Checklist: 

- [x] Invite to CommComm GitHub Team (and Node.js GitHub org, if not already member)
- [x] Submit PR to add to the [commcomm email alias](https://github.com/nodejs/email/blob/master/iojs.org/aliases.json#L96)

### CODE REVIEW

**Comment by bnb** [comment]
@codeekage could you please confirm that the listed email address is the one that should be added to the CommComm alias?

**Comment by codeekage** [comment]
confirm the use of agiriabrahamjunior@nodejs.africa as alias email.

**Comment by codeekage** [comment]
Thank you @chowdhurian

**Comment by codeekage** [comment]
Can this be merged or its more approvals?

**Comment by WaleedAshraf** [comment]
@codeekage have you submitted a PR to add to the[ commcomm email alias](https://github.com/nodejs/email/blob/master/iojs.org/aliases.json#L123) ?

**Comment by codeekage** [comment]
@WaleedAshraf  I just did thank you!! 🙏

**Comment by bnb** [comment]
Going to merge this. Welcome @codeekage 🎊

**Pull request merged**
