### PR TITLE
Adding Jenn, Tierney, Michael, Olivia, and Richard as members

### PR DESCRIPTION
**Pull request by nebrius**
Now that Jenn and Tierny are going to [share the secretary position](https://github.com/nodejs/community-committee/issues/64), we need to add them as members first. This PR adds them as members and lists them as the secretary.

@nodejs/community-committee adding members requires a vote, can you please indicate here if you vote yes? If you want to vote no, you can vote no here, or contact me via email if you don't want to vote publicly (it's listed on my github page).

### CODE REVIEW

**Comment by hackygolucky** [comment]
I'm down to add them since we don't technically have this written yet, but this is counter to what we've discussed about the process moving forward to adding members(be marked as observing in meetings, attend min # meetings, some participation/input along the way up to the 3 month mark). Unless it's been three months and then all of this is moot anyway 😆

**Comment by renrutnnej** [comment]
That's a really good point @hackygolucky. We should probably not move forward with circumventing the process, since there's no rush or deadline to become a member (at least in my case).

**Comment by nebrius** [comment]
Yep, definitely a good point. Let's chat about this in the meeting.

**Comment by nebrius** [comment]
As we discussed in the last meeting, this adds @mhdawson, @pup, and @RichardLitt to the list. I believe the three of you have already expressed interest in joining, but please let me know if I'm not remembering correctly!

Note: @nodejs/community-committee we will need to revote on the new list of members, so please let me know here, or in the next meeting, how you vote. Thanks!

**Comment by pup** [comment]
should the name of this pull request be changed, then?

**Comment by hackygolucky** [comment]
As voting members, @ashleygwilliams @rachelnicole @MylesBorins @emilyrose @jpwesselink @MylesBorins @rvagg @msmichellegar @nebrius 

could you please vote by approving this PR for these contributors being added as members? It was determined in the last CommComm meeting that it would be appropriate to add them as they've been participating and contributing prior to us having the rules in place for membership, so it made sense for us to go ahead and add them as thanks and then lock in the process moving forward for future members. We did not have quorum of members in our meeting today to close this vote but had a fantastic showing of observers working towards membership.

**Comment by rachelnicole** [comment]
👍

**Comment by nebrius** [comment]
We now have six votes from the following people:

@williamkapke 
@hackygolucky 
@gr2m 
@MylesBorins 
@nebrius
@rachelnicole 

This is greater than 50%, and so the vote is successful. Welcome all new members!! 🎉🎉🎉

**Comment by pup** [comment]
yay! just for clarification, why are there two commcomm teams now, @nodejs slash commcomm-members and @nodejs slash community-committee?

**Comment by nebrius** [comment]
> yay! just for clarification, why are there two commcomm teams now, @nodejs slash commcomm-members and @nodejs slash community-committee?

I'm actually not sure tbh. I always use @nodejs slash community-committee myself

**Comment by pup** [comment]
so i'm not on the slash community-committee team (i'm also not on slash members) and also @bnb isn't on either of them. maybe we could remove one of the two? it seems confusing

**Comment by pup** [comment]
@nebrius looks like i'm the only one that's actually been _added_?

**Comment by nebrius** [comment]
@pup, looks like I don't have permission to add folks, since I didn't create the team and am not an org owner. @hackygolucky, can you delete the @nodejs /commcomm-members and @nodejs /community-committee-contributors teams, and then add the new members to @nodejs /community-committee team?

**Comment by mhdawson** [comment]
My flight is leaving soon, otherwise I'd do it now.  I'll try to check on monday and if @hackygolucky has not beat me to it I'll update.  If you don't see it happen on Monday I'd be happy to get a "reminder'

**Comment by nebrius** [comment]
@mhdawson ping! If you have time, would you mind updating the teams?

**Comment by mhdawson** [comment]
Sorry been busy few weeks. @nebrius Looking at the teams it looks like they have been updated.  Let me know if there is still something that needs to be updated.

**Comment by nebrius** [comment]
Sorry, I forgot to update here that, yes, the teams have been updated already. Thanks for following up @mhdawson!

**Pull request merged**
