### PR TITLE
Create ONBOARDING.md

### PR DESCRIPTION
**Pull request by bnb**
Created a quick initial document for on-boarding new CommComm members. Wanted to throw something together so we can begin discussing and building upon it 👍

### CODE REVIEW

**Comment by hackygolucky** [comment]
I think we should not make assumptions on how versed folks are with 1. Open source practices and 2. Node.js project practices for interacting and administrative duties related to our work, since many of the contributions for our work can live outside of the GitHub project workspace.

**Comment by chowdhurian** [comment]
Agreed ^^ Added some material to start.

**Comment by bnb** [comment]
@chowdhurian @hackygolucky any thoughts on adding a small section about the "consensus seeking" model?

**Comment by chowdhurian** [comment]
> any thoughts on adding a small section about the "consensus seeking" model?

It's the cornerstone of the process here, crucial to buy-in and cooperation. Added!

**Comment by codeekage** [comment]
should process around becoming a members get added in this document?

**Comment by bnb** [comment]
@codeekage nope, that belongs in other documentation. The explicit goal of this is to ensure that once we do accept a new member, that we have a laid out process to follow.

**Comment by hackygolucky** [comment]
This document looks good overall to me. I think a helpful process to call out is the minimum amount of time required for review before we can merge a document. It isn't consistent across the project, so making sure it is known would be nice here. 

[This whole section is particularly helpful to mention](https://github.com/nodejs/community-committee/blob/master/COLLABORATOR_GUIDE.md#accepting-modifications) but the hours specifically
>Before landing pull requests, sufficient time should be left for input from other Collaborators. Leave at least 48 hours during the week and 72 hours over weekends to account for international time differences and work schedules. Trivial changes (e.g. typos or content changes) may be landed after a shorter delay.
>Where there is no disagreement amongst Collaborators, a pull request may be landed given appropriate review. Where there is discussion amongst Collaborators, consensus should be sought if possible. The lack of consensus may indicate the need to elevate discussion to the Community Committee Members for resolution

We can discuss whether it should be consistent across the project in another issue :)

**Comment by bnb** [comment]
Copy/pasted that section @hackygolucky 👍 

Going to land this. Let's iterate from here on! 🎊

**Pull request merged**
